#!/bin/bash
CURDATE=`date`
sendmail -oi web-Zzu5p4@mail-tester.com << EOF
From: Your User <web-Zzu5p4@mail-tester.com>
To: support@vip-consult.cu.ok
Subject: SERVER INFO: Email test on $CURDATE

SERVER INFO: Email test on $CURDATE

EOF
